version: "3.9"

services:
  # app is the name of the service
  app:
    build:
      context: .
      args:
       - DEV=true
    ports:
    # Port mappings. Maps Port 8000 from local machine to Port 8000 inside docker container
     - "8000:8000"
    volumes:
    # Mapping directories from system to docker container.
    # Update changes to be reflected in the container.
     - ./app:/app
    command: >
     sh -c "python manage.py runserver 0.0.0.0:8000"
